# Generated by Django 4.1.1 on 2022-11-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
        
        delete from django_migrations where app = "main" or app = "accounts";

        drop table if exists main_but_departement;
        drop table if exists main_semester_ue;
        drop table if exists main_student_group;
        drop table if exists main_course_but;
        drop table if exists main_course;
        drop table if exists main_establishment;
        drop table if exists main_ue;
        drop table if exists main_year;
        drop table if exists main_usefullink;
        drop table if exists main_student;
        drop table if exists main_group;
        drop table if exists main_but;
        drop table if exists main_department;
        drop table if exists main_competence;
        drop table if exists main_semester;
        
        """)
    ]
