# Generated by Django 4.1.1 on 2022-12-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='departments',
        ),
        migrations.AddField(
            model_name='professor',
            name='establishments',
            field=models.ManyToManyField(to='main.establishment'),
        ),
    ]
