# Generated by Django 4.1.1 on 2022-11-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_group_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ue')),
            ],
        ),
        migrations.AddField(
            model_name='year',
            name='semester',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.semester'),
        ),
    ]
