# Generated by Django 4.1.1 on 2022-12-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_professor_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='establishment',
        ),
        migrations.AddField(
            model_name='establishment',
            name='departments',
            field=models.ManyToManyField(to='main.department'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(default=0.0)),
                ('coef', models.FloatField(blank=True, default=1.0)),
                ('evaluation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.evaluation')),
            ],
        ),
    ]
