# Generated by Django 4.1.1 on 2022-12-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ue', models.ManyToManyField(to='main.ue')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='resource',
            field=models.ManyToManyField(to='main.resource'),
        ),
    ]
