# Generated by Django 4.1.1 on 2022-12-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_department_establishment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='departments',
            field=models.ManyToManyField(related_name='establishments', to='main.department'),
        ),
    ]
