# Generated by Django 4.1.1 on 2022-12-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resource_professor_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='but',
            old_name='department',
            new_name='departments',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='BUT',
            new_name='BUTs',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='ue',
            new_name='ues',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='ue',
            new_name='ues',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='groups',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='resource',
        ),
        migrations.AddField(
            model_name='professor',
            name='departments',
            field=models.ManyToManyField(to='main.department'),
        ),
        migrations.AddField(
            model_name='professor',
            name='resources',
            field=models.ManyToManyField(blank=True, to='main.resource'),
        ),
    ]
