# Generated by Django 4.1.1 on 2022-11-30 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ue_group_year_alter_year_name_semester_year_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.year'),
        ),
    ]
