# Generated by Django 4.1.4 on 2022-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resource_professor_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='department',
        ),
        migrations.AlterField(
            model_name='professor',
            name='resource',
            field=models.ManyToManyField(blank=True, to='main.resource'),
        ),
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.ManyToManyField(to='main.department'),
        ),
    ]
