# Generated by Django 4.1.1 on 2022-12-11 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_rename_department_but_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(to='main.department')),
                ('resources', models.ManyToManyField(blank=True, to='main.resource')),
            ],
        ),
    ]
