# Generated by Django 4.1.1 on 2022-12-15 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_establishment_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='establishments',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='resources',
        ),
        migrations.AddField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
