# Generated by Django 4.1.1 on 2022-12-15 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_administrator_establishments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='departments',
        ),
        migrations.AddField(
            model_name='department',
            name='establishment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establishment', to='main.establishment'),
        ),
        migrations.AddField(
            model_name='ue',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
    ]
