# Generated by Django 4.1.1 on 2022-12-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_student_department_alter_student_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='user',
            new_name='student',
        ),
    ]
