# Generated by Django 4.1.1 on 2022-12-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_professor_department_alter_professor_resource_and_more'),
        ('main', '0009_remove_evaluation_ue_evaluation_ue'),
    ]

    operations = [
    ]
