# Generated by Django 4.1.1 on 2022-12-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_user_grade_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='establishments',
        ),
        migrations.AddField(
            model_name='professor',
            name='departments',
            field=models.ManyToManyField(to='main.department'),
        ),
    ]
