# Generated by Django 4.1.1 on 2022-12-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_student_groups_student_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
    ]
