# Generated by Django 4.1.1 on 2022-12-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_semester_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='ues',
        ),
        migrations.RemoveField(
            model_name='ue',
            name='department',
        ),
        migrations.AddField(
            model_name='resource',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
        migrations.AddField(
            model_name='semester',
            name='resources',
            field=models.ManyToManyField(related_name='semesters', to='main.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ues',
            field=models.ManyToManyField(related_name='resources', to='main.ue'),
        ),
    ]
