# Generated by Django 4.1.1 on 2022-12-19 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_evaluation_semester_remove_evaluation_ues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='ue',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='department',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='resources',
        ),
        migrations.AddField(
            model_name='resource',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='semester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.semester'),
        ),
    ]
