# Generated by Django 4.1.1 on 2022-12-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_student_group_student_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='professors', to='main.resource'),
        ),
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(related_name='students', to='main.group'),
        ),
    ]
