# Generated by Django 4.1.1 on 2023-01-14 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_grade_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ue',
            name='department',
        ),
        migrations.AddField(
            model_name='competence',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
        migrations.AddField(
            model_name='competence',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ue',
            name='competence',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.competence'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
