# Generated by Django 4.1.1 on 2023-01-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_evaluation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='min_competence_grade',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='nb_competence_required',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
